export interface MediaItem {
  id: string
  title: string
  image: string
  link: string
}

export interface MediaData {
  completed: MediaItem[]
  currentlyWatching: MediaItem[]
}

export const animeData: MediaData = {
  completed: [
    {
      id: "1",
      title: "Reborn As A Vending Machine",
      image: "Reborn As A Vending Machine.jpg",
      link: "https://hianime.to/reborn-as-a-vending-machine-now-i-wander-the-dungeon-18483",
    },
    {
      id: "2",
      title: "Dan Da Dan",
      image: "Dan Da Dan.jpg",
      link: "https://hianime.to/dan-da-dan-19319",
    },
    {
      id: "3",
      title: "Lord Of Mysteries",
      image: "Lord Of Mysteries.jpg",
      link: "https://hianime.to/lord-of-mysteries-19802",
    },
    {
      id: "4",
      title: "In Another World With My Smartphone",
      image: "In Another World With My Smartphone.jpg",
      link: "http://hianime.to/in-another-world-with-my-smartphone-6705",
    },
    {
      id: "5",
      title: "Fire Force",
      image: "Fire Force.jpg",
      link: "https://hianime.to/fire-force-979",
    },
    {
      id: "6",
      title: "The Brilliant Healer's New Life in the Shadows",
      image: "The Brilliant Healer's New Life in the Shadows.jpg",
      link: "https://hianime.to/the-brilliant-healers-new-life-in-the-shadows-19553",
    },
    {
      id: "7",
      title: "The Unaware Atelier Master",
      image: "The Unaware Atelier Master.jpg",
      link: "https://hianime.to/the-unaware-atelier-master-19569",
    },
    {
      id: "8",
      title: "Orient",
      image: "Orient.jpg",
      link: "https://hianime.to/orient-17468",
    },
    {
      id: "9",
      title: "I've Been Killing Slimes for 300 Years and Maxed Out My Level",
      image: "I've Been Killing Slimes for 300 Years and Maxed Out My Level.jpg",
      link: "https://hianime.to/ive-been-killing-slimes-for-300-years-and-maxed-out-my-level-15557",
    },
    {
      id: "10",
      title: "The Daily Life of a Middle-Aged Online Shopper in Another World",
      image: "The Daily Life of a Middle-Aged Online Shopper in Another World.jpg",
      link: "https://hianime.to/the-daily-life-of-a-middle-aged-online-shopper-in-another-world-19468",
    },
    {
      id: "11",
      title: "Shangri-La Frontier",
      image: "SLF.jpg",
      link: "https://hianime.to/shangri-la-frontier-18567",
    },
    {
      id: "12",
      title: "The Red Ranger Becomes an Adventurer in Another World",
      image: "The Red Ranger Becomes an Adventurer in Another World.jpg",
      link: "https://hianime.to/the-red-ranger-becomes-an-adventurer-in-another-world-19463",
    },
    {
      id: "13",
      title: "Solo Leveling",
      image: "Solo Leveling.jpg",
      link: "https://hianime.to/solo-leveling-18718",
    },
    {
      id: "14",
      title: "Dr. Stone",
      image: "Dr Stone.jpg",
      link: "https://hianime.to/dr-stone-175",
    },
    {
      id: "15",
      title: "Even Given the Worthless \“Appraiser\” Class, I’m Actually the Strongest",
      image: "Even Given the Worthless \“Appraiser\” Class, I’m Actually the Strongest.jpg",
      link: "https://hianime.to/even-given-the-worthless-appraiser-class-im-actually-the-strongest-19457",
    },
    {
      id: "16",
      title: "Magic Maker: How to Make Magic in Another World",
      image: "Magic Maker How to Make Magic in Another World.jpg",
      link: "https://hianime.to/magic-maker-how-to-make-magic-in-another-world-19469",
    },
    {
      id: "17",
      title: "Pokémon Horizons",
      image: "Pokémon Horizons.jpg",
      link: "https://hianime.to/pokemon-horizons-the-series-18397",
    },
    {
      id: "18",
      title: "Magi Adventure of Sinbad",
      image: "Magi Adventure of Sinbad.jpg",
      link: "https://hianime.to/magi-adventure-of-sinbad-602",
    },
    {
      id: "19",
      title: "Headhunted to Another World From Salaryman to Big Four",
      image: "Headhunted to Another World From Salaryman to Big Four.jpg",
      link: "https://hianime.to/headhunted-to-another-world-from-salaryman-to-big-four-19454",
    },
    {
      id: "20",
      title: "I'm a Noble on the Brink of Ruin, So I Might as Well Try Mastering Magic",
      image: "I'm a Noble on the Brink of Ruin, So I Might as Well Try Mastering Magic.jpg",
      link: "https://hianime.to/im-a-noble-on-the-brink-of-ruin-so-i-might-as-well-try-mastering-magic-19458",
    },
    {
      id: "21",
      title: "Bogus Skill",
      image: "Bogus Skill.jpg",
      link: "https://hianime.to/bogus-skill-lesslessfruitmastergreatergreater-about-that-time-i-became-able-to-eat-unlimited-numbers-of-skill-fruits-that-kill-you-19465",
    },
    {
      id: "22",
      title: "Possibly the Greatest Alchemist of All Time",
      image: "Possibly the Greatest Alchemist of All Time.jpg",
      link: "https://hianime.to/possibly-the-greatest-alchemist-of-all-time-19451",
    },
    {
      id: "23",
      title: "That Time I Got Reincarnated as a Slime",
      image: "That Time I Got Reincarnated as a Slime.jpg",
      link: "https://hianime.to/that-time-i-got-reincarnated-as-a-slime-429",
    },
    {
      id: "24",
      title: "Blue Lock",
      image: "Blue Lock.jpg",
      link: "https://hianime.to/blue-lock-17889",
    },
    {
      id: "25",
      title: "As a Reincarnated Aristocrat, I'll Use My Appraisal Skill to Rise in the World",
      image: "As a Reincarnated Aristocrat, I'll Use My Appraisal Skill to Rise in the World.jpg",
      link: "https://hianime.to/as-a-reincarnated-aristocrat-ill-use-my-appraisal-skill-to-rise-in-the-world-19127",
    },
    {
      id: "26",
      title: "The Healer Who Was Banished From His Party, Is, in Fact, the Strongest",
      image: "The Healer Who Was Banished From His Party, Is, in Fact, the Strongest.jpg",
      link: "https://hianime.to/the-healer-who-was-banished-from-his-party-is-in-fact-the-strongest-19345",
    },
    {
      id: "27",
      title: "Bleach",
      image: "Bleach.jpg",
      link: "https://hianime.to/bleach-806",
    },
    {
      id: "28",
      title: "Mechanical Arms",
      image: "Mechanical Arms.jpeg",
      link: "https://hianime.to/mechanical-arms-19354",
    },
    {
      id: "29",
      title: "Loner Life in Another World",
      image: "Loner Life in Another World.jpg",
      link: "https://hianime.to/loner-life-in-another-world-19337",
    },
    {
      id: "30",
      title: "Vermeil in Gold",
      image: "Vermeil in Gold.jpg",
      link: "https://hianime.to/vermeil-in-gold-18081",
    },
    {
      id: "31",
      title: "My Hero Academia",
      image: "Hero Academia.jpg",
      link: "https://hianime.to/my-hero-academia-322",
    },
    {
      id: "32",
      title: "Wistoria Wand & Sword",
      image: "Wistoria.jpg",
      link: "https://hianime.to/wistoria-wand-and-sword-19239",
    },
    {
      id: "33",
      title: "Failure Frame",
      image: "Failure Frame.jpg",
      link: "https://hianime.to/failure-frame-i-became-the-strongest-and-annihilated-everything-with-low-level-spells-19237",
    },
    {
      id: "34",
      title: "The King's Avatar",
      image: "The King's Avatar.jpg",
      link: "https://hianime.to/the-kings-avatar-521",
    },
    {
      id: "35",
      title: "The Unwanted Undead Adventurer",
      image: "The Unwanted Undead Adventurer.jpg",
      link: "https://hianime.to/the-unwanted-undead-adventurer-18808",
    },
    {
      id: "36",
      title: "Magical Warfare",
      image: "Magical Warfare.jpg",
      link: "https://hianime.to/magical-warfare-7859",
    },
    {
      id: "37",
      title: "The Asterisk War",
      image: "The Asterisk War.jpg",
      link: "https://hianime.to/the-asterisk-war-3820",
    },
    {
      id: "38",
      title: "Grandpa and Grandma Turn Young Again",
      image: "Grandpa and Grandma Turn Young Again.jpg",
      link: "https://hianime.to/grandpa-and-grandma-turn-young-again-19134",
    },
    {
      id: "39",
      title: "My Daughter Left the Nest and Returned an S-Rank Adventurer",
      image: "My Daughter Left the Nest and Returned an S-Rank Adventurer.jpeg",
      link: "https://hianime.to/my-daughter-left-the-nest-and-returned-an-s-rank-adventurer-18565",
    },
    {
      id: "40",
      title: "The Dungeon of Black Company",
      image: "The Dungeon of Black Company.jpg",
      link: "https://hianime.to/the-dungeon-of-black-company-15801",
    },
    {
      id: "41",
      title: "High Card",
      image: "High Card.jpg",
      link: "https://hianime.to/high-card-18313",
    },
    {
      id: "42",
      title: "K-Project",
      image: "K-Project.jpg",
      link: "https://hianime.to/k-project-1461",
    },
    {
      id: "43",
      title: "The Misfit of Demon King Academy",
      image: "The Misfit of Demon King Academy.jpg",
      link: "https://hianime.to/the-misfit-of-demon-king-academy-1768",
    },
    {
      id: "44",
      title: "Knight's & Magic",
      image: "Knight's & Magic.jpg",
      link: "https://hianime.to/knights-magic-2919",
    },
    {
      id: "45",
      title: "The 8th son? Are you kidding me?",
      image: "The 8th son Are you kidding me.jpg",
      link: "https://hianime.to/the-8th-son-are-you-kidding-me-7283",
    },
    {
      id: "46",
      title: "The Irregular at Magic High School",
      image: "The Irregular at Magic High School.jpg",
      link: "https://hianime.to/the-irregular-at-magic-high-school-1344?ref=search",
    },
    {
      id: "47",
      title: "Full-Time Magister",
      image: "Full-Time Magister.jpg",
      link: "https://hianime.to/full-time-magister-2189",
    },
    {
      id: "48",
      title: "Isekai Cheat Magician",
      image: "Isekai Cheat Magician.jpg",
      link: "https://hianime.to/isekai-cheat-magician-9632",
    },
    {
      id: "49",
      title: "Villainess Level 99",
      image: "Villainess Level 99.jpg",
      link: "https://hianime.to/villainess-level-99-i-may-be-the-hidden-boss-but-im-not-the-demon-lord-18829",
    },
    {
      id: "50",
      title: "Chillin' in My 30s after Getting Fired from the Demon King's Army",
      image: "Chillin' in My 30s after Getting Fired from the Demon King's Army.jpg",
      link: "https://hianime.to/chillin-in-my-30s-after-getting-fired-from-the-demon-kings-army-18294",
    },
    {
      id: "51",
      title: "Reincarnated as a Sword",
      image: "Reincarnated as a Sword.jpg",
      link: "https://hianime.to/reincarnated-as-a-sword-18161",
    },
    {
      id: "51",
      title: "Akashic Records of Bastard Magic Instructor",
      image: "Akashic Records of Bastard Magic Instructor.jpg",
      link: "https://hianime.to/akashic-records-of-bastard-magic-instructor-2674",
    },
    {
      id: "52",
      title: "World Trigger",
      image: "World Trigger.jpg",
      link: "https://hianime.to/world-trigger-1356",
    },
    {
      id: "53",
      title: "My Unique Skill Makes Me OP Even at Level 1",
      image: "My Unique Skill Makes Me OP Even at Level 1.jpg",
      link: "https://hianime.to/my-unique-skill-makes-me-op-even-at-level-1-18479",
    },
    {
      id: "54",
      title: "Chivalry of a Failed Knight",
      image: "Chivalry of a Failed Knight.jpg",
      link: "https://hianime.to/chivalry-of-a-failed-knight-1406",
    },
    {
      id: "55",
      title: "Spirit Chronicles",
      image: "Spirit Chronicles.jpg",
      link: "https://hianime.to/spirit-chronicles-17333",
    },
    {
      id: "56",
      title: "Plunderer",
      image: "Plunderer.jpg",
      link: "https://hianime.to/plunderer-5815",
    },
    {
      id: "57",
      title: "Banished From the Heroes' Party",
      image: "Banished From the Heroes' Party.jpg",
      link: "https://hianime.to/banished-from-the-heroes-party-17372",
    },
    {
      id: "58",
      title: "Reign of the Seven Spellblades",
      image: "Reign of the Seven Spellblades.jpg",
      link: "https://hianime.to/reign-of-the-seven-spellblades-18488",
    },
    {
      id: "59",
      title: "Welcome to Demon School! Iruma-kun",
      image: "Welcome to Demon School! Iruma-kun.jpeg",
      link: "https://hianime.to/welcome-to-demon-school-iruma-kun-966",
    },
    {
      id: "60",
      title: "The Demon Sword Master of Excalibur Academy",
      image: "The Demon Sword Master of Excalibur Academy.jpg",
      link: "https://hianime.to/the-demon-sword-master-of-excalibur-academy-18584",
    },
    {
      id: "61",
      title: "A Returner's Magic Should Be Special",
      image: "Returner.jpg",
      link: "https://hianime.to/a-returners-magic-should-be-special-18600",
    },
    {
      id: "62",
      title: "My Instant Death Ability is So Overpowered, No One in This Other World Stands a Chance Against Me!",
      image: "My Instant Death Ability is So Overpowered, No One in This Other World Stands a Chance Against Me!.jpg",
      link: "https://hianime.to/my-instant-death-ability-is-so-overpowered-no-one-in-this-other-world-stands-a-chance-against-me-18847",
    },
    {
      id: "63",
      title: "Parasyte -the maxim-",
      image: "Parasyte -the maxim-.jpg",
      link: "https://hianime.to/parasyte-the-maxim-136",
    },
    {
      id: "64",
      title: "Chillin' in Another World with Level 2 Super Cheat Powers",
      image: "Chillin' in Another World with Level 2 Super Cheat Powers.jpg",
      link: "https://hianime.to/chillin-in-another-world-with-level-2-super-cheat-powers-19129",
    },
    {
      id: "65",
      title: "Black Clover",
      image: "Black Clover.jpg",
      link: "https://hianime.to/black-clover-2404",
    },
    {
      id: "66",
      title: "Wise Man's Grandchild",
      image: "Wise Man's Grandchild.jpg",
      link: "https://hianime.to/wise-mans-grandchild-5498",
    },
    {
      id: "67",
      title: "The Devil is a Part-Timer",
      image: "The Devil is a Part-Timer.jpg",
      link: "https://hianime.to/the-devil-is-a-part-timer-724",
    },
    {
      id: "68",
      title: "The World's Finest Assassin Gets Reincarnated in a Different World as an Aristocrat",
      image: "The World's Finest Assassin Gets Reincarnated in a Different World as an Aristocrat.jpg",
      link: "https://hianime.to/the-worlds-finest-assassin-gets-reincarnated-in-a-different-world-as-an-aristocrat-17482",
    },
    {
      id: "69",
      title: "The Iceblade Sorcerer Shall Rule the World",
      image: "The Iceblade Sorcerer Shall Rule the World.jpg",
      link: "https://hianime.to/the-iceblade-sorcerer-shall-rule-the-world-18291",
    },
    {
      id: "70",
      title: "Berserk of Gluttony",
      image: "Berserk of Gluttony.jpg",
      link: "https://hianime.to/berserk-of-gluttony-18593",
    },
    {
      id: "71",
      title: "I Was Reincarnated as the 7th Prince so I Can Take My Time Perfecting My Magical Ability",
      image: "I Was Reincarnated as the 7th Prince so I Can Take My Time Perfecting My Magical Ability.jpg",
      link: "https://hianime.to/i-was-reincarnated-as-the-7th-prince-so-i-can-take-my-time-perfecting-my-magical-ability-19132",
    },
    {
      id: "72",
      title: "The Wrong Way to Use Healing Magic",
      image: "The Wrong Way to Use Healing Magic.jpg",
      link: "https://hianime.to/the-wrong-way-to-use-healing-magic-18838",
    },
    {
      id: "73",
      title: "Am I Actually the Strongest?",
      image: "Am I Actually the Strongest.jpg",
      link: "https://hianime.to/am-i-actually-the-strongest-18481",
    },
    {
      id: "74",
      title: "Ninja Kamui",
      image: "Ninja Kamui.jpg",
      link: "https://hianime.to/ninja-kamui-19018",
    },
    {
      id: "75",
      title: "The Daily Life of the Immortal King",
      image: "The Daily Life of the Immortal King.jpg",
      link: "https://hianime.to/the-daily-life-of-the-immortal-king-2945",
    },
    {
      id: "76",
      title: "My Isekai Life: I Gained a Second Character Class and Became the Strongest Sage in the World",
      image: "My Isekai Life I Gained a Second Character Class and Became the Strongest Sage in the World.jpg",
      link: "https://hianime.to/my-isekai-life-i-gained-a-second-character-class-and-became-the-strongest-sage-in-the-world-17502",
    },
    {
      id: "77",
      title: "The Reincarnation of the Strongest Exorcist in Another World",
      image: "The Reincarnation of the Strongest Exorcist in Another World.jpg",
      link: "https://hianime.to/the-reincarnation-of-the-strongest-exorcist-in-another-world-18290",
    },
    {
      id: "78",
      title: "Sword Art Online",
      image: "Sword Art Online.jpg",
      link: "https://hianime.to/sword-art-online-2274",
    },
    {
      id: "79",
      title: "The Greatest Demon Lord Is Reborn as a Typical Nobody",
      image: "The Greatest Demon Lord Is Reborn as a Typical Nobody.jpg",
      link: "https://hianime.to/the-greatest-demon-lord-is-reborn-as-a-typical-nobody-17682",
    },
    {
      id: "80",
      title: "Black Summoner",
      image: "Black Summoner.jpg",
      link: "https://hianime.to/black-summoner-18088",
    },
    {
      id: "81",
      title: "Ragna Crimson",
      image: "Ragna Crimson.jpg",
      link: "https://hianime.to/ragna-crimson-18566",
    },
    {
      id: "82",
      title: "Overlord",
      image: "Overlord.jpg",
      link: "https://hianime.to/overlord-552",
    },
    {
      id: "83",
      title: "The Aristocrat's Otherworldly Adventure",
      image: "The Aristocrat's Otherworldly Adventure.jpeg",
      link: "https://hianime.to/the-aristocrats-otherworldly-adventure-serving-gods-who-go-too-far-18355",
    },
    {
      id: "84",
      title: "One Punch Man",
      image: "One Punch Man.jpg",
      link: "https://hianime.to/one-punch-man-63",
    },
    {
      id: "85",
      title: "Tsukimichi -Moonlit Fantasy-",
      image: "Tsukimichi -Moonlit Fantasy-.jpg",
      link: "https://hianime.to/tsukimichi-moonlit-fantasy-17241",
    },
    {
      id: "86",
      title: "The Rising of the Shield Hero",
      image: "The Rising of the Shield Hero.jpeg",
      link: "https://hianime.to/the-rising-of-the-shield-hero-524",
    },
    {
      id: "87",
      title: "The Eminence in Shadow",
      image: "The Eminence in Shadow.jpg",
      link: "https://hianime.to/the-eminence-in-shadow-17473",
    },
    {
      id: "88",
      title: "Kaiju No. 8",
      image: "Kaiju No 8.jpg",
      link: "https://hianime.to/kaiju-no-8-19145",
    },
    {
      id: "89",
      title: "Classroom of the Elite",
      image: "Classroom of the Elite.jpg",
      link: "https://hianime.to/classroom-of-the-elite-713",
    },
    {
      id: "90",
      title: "I Got a Cheat Skill in Another World and Became Unrivaled in The Real World, Too",
      image: "I Got a Cheat Skill in Another World and Became Unrivaled in The Real World, Too.jpg",
      link: "https://hianime.to/i-got-a-cheat-skill-in-another-world-and-became-unrivaled-in-the-real-world-too-18343",
    },
    {
      id: "91",
      title: "Mashle: Magic and Muscles",
      image: "Mashle Magic and Muscle.jpg",
      link: "https://hianime.to/mashle-magic-and-muscles-18339",
    },
    {
      id: "92",
      title: "Death Note",
      image: "Death Note.jpg",
      link: "https://hianime.to/death-note-60",
    },
    {
      id: "93",
      title: "Attack on Titan",
      image: "Attack on Titan.jpg",
      link: "https://hianime.to/attack-on-titan-112",
    },
    {
      id: "94",
      title: "Naruto",
      image: "Naruto.jpg",
      link: "https://hianime.to/naruto-677",
    },
    {
      id: "95",
      title: "Demon Slayer",
      image: "Demon Slayer.jpg",
      link: "https://hianime.to/demon-slayer-kimetsu-no-yaiba-47",
    },
    {
      id: "96",
      title: "Jujutsu Kaisen",
      image: "Jujutsu Kaisen.jpg",
      link: "https://hianime.to/jujutsu-kaisen-tv-534",
    },

    {
      id: "97",
      title: "Pokémon",
      image: "Pokémon.jpg",
      link: "https://hianime.to/pokemon-2097",
    },
    {
      id: "98",
      title: "Beyblade",
      image: "Beyblade.jpg",
      link: "https://hianime.to/beyblade-metal-fusion-5115",
    },
    {
      id: "99",
      title: "Doraemon",
      image: "Doraemon.jpg",
      link: "https://hianime.to/doraemon-2005-1551",
    },
    {
      id: "100",
      title: "Shin Chan",
      image: "Shin Chan.jpg",
      link: "https://hianime.to/shin-chan-1058",
    },
    {
      id: "101",
      title: "Ninja Hattori",
      image: "Ninja Hattori.jpg",
      link: "https://hianime.to/ninja-hattori-kun-4234",
    },
    {
      id: "102",
      title: "The Water Magician",
      image: "Water Magician.jpg",
      link: "https://hianime.to/the-water-magician-19770",
    }
  ],
  currentlyWatching: [
    {
      id: "4",
      title: "One Piece",
      image: "One Piece.jpg",
      link: "https://hianime.to/one-piece-100",
    },
  ],
}

export const mangaData: MediaData = {
  completed: [
    {
      id: "6",
      title: "My Hero Academia",
      image: "/Hero Academia.jpg",
      link: "https://mangafire.to/manga/my-hero-academiaa.kkvk9",
    },
    {
      id: "7",
      title: "Demon Slayer",
      image: "/Demon Slayer.jpg",
      link: "https://mangafire.to/manga/kimetsu-no-yaibaa.7j6",
    },
    {
      id: "8",
      title: "Doctor Stone",
      image: "/Dr Stone.jpg",
      link: "https://mangafire.to/manga/dr-stonee.qkm13",
    },
    {
      id: "9",
      title: "Kaiju No. 8 ",
      image: "/Kaiju No 8.jpg",
      link: "https://mangafire.to/manga/kaiju-no-88.yqqv0",
    },
    {
      id: "10",
      title: "Bleach",
      image: "/Bleach.jpg",
      link: "http://mangafire.to/manga/bleachh.027",
    },
  ],
  currentlyWatching: [
    {
      id: "8",
      title: "One Piece",
      image: "/One Piece.jpg",
      link: "https://mangafire.to/manga/one-piecee.dkw",
    },
    {
      id: "9",
      title: "Blue Lock",
      image: "Blue Lock.jpg",
      link: "https://mangafire.to/manga/blue-lockk.kw9j9",
    },
    {
      id: "10",
      title: "Black Clover",
      image: "/Black Clover.jpg",
      link: "https://mangafire.to/manga/black-cloverr.pp4",
    },
    {
      id: "11",
      title: "Boruto: Blue Votrex",
      image: "/Boruto.jpg",
      link: "https://mangafire.to/manga/boruto-two-blue-vortexx.mvymp",
    },
    {
      id: "12",
      title: "Shangri-La Frontier",
      image: "/SLF.jpg",
      link: "https://mangafire.to/manga/shangri-la-frontier-kusoge-hunter-kamige-ni-idoman-to-suu.92lx",
    },
    {
      id: "13",
      title: "Wistoria Wand & Sword",
      image: "/Wistoria.jpg",
      link: "https://mangafire.to/manga/wistoria-wand-and-swordd.02n57",
    },
    {
      id: "14",
      title: "Failure Frame",
      image: "/Failure Frame.jpg",
      link: "https://mangafire.to/manga/hazure-waku-no-joutai-ijou-skill-de-saikyou-ni-natta-ore-ga-subete-wo-juurin-suru-madee.qxp75",
    },
  ],
}

export const manhwaData: MediaData = {
  completed: [
    {
      id: "15",
      title: "Solo Leveling",
      image: "/Solo Leveling.jpg",
      link: "https://asuracomic.net/series/solo-leveling-63564fed",
    },
    {
      id: "16",
      title: "Noblesse",
      image: "/Noblesse.jpg",
      link: "https://likemanga.ink/noblesse-manhwa-1241/",
    },
    {
      id: "21",
      title: "Greatest Estate Developer",
      image: "/Greatest Estate Developer.jpeg",
      link: "https://asuracomic.net/series/the-greatest-estate-developer-10375520",
    },
    {
      id: "17",
      title: "A Returner's Magic Should Be Special",
      image: "/Returner.jpg",
      link: "https://likemanga.ink/a-returner%E2%80%99s-magic-should-be-special-1845/",
    },
    {
      id: "18",
      title: "Tomb Raider King",
      image: "/Tomb Raider.jpg",
      link: "https://likemanga.ink/tomb-raider-king-4921/",
    },
    {
      id: "19",
      title: "Questism",
      image: "/Questism.webp",
      link: "https://likemanga.ink/quest-supremacy-3651/",
    },
  ],
  currentlyWatching: [
    {
      id: "20",
      title: "Catastrophic Necromancer",
      image: "/Catastrophic Necromancer.png",
      link: "https://likemanga.ink/catastrophic-necromancer-3060/",
    },
  
    {
      id: "22",
      title: "The Max Level Player's 100th Regression",
      image: "/The Max Level Player's 100th Regression.webp",
      link: "https://likemanga.ink/the-maxlevel-player%E2%80%99s-100th-regression-8687/",
    },
    {
      id: "23",
      title: "Nano Machine",
      image: "/Nano Machine.jpg",
      link: "https://likemanga.ink/nano-machine-2512/",
    },
    {
      id: "24",
      title: "Dragon Tamer",
      image: "/Dragon Tamer.jpg",
      link: "https://likemanga.ink/worthless-profession-dragon-tamer-15665/",
    },
    {
      id: "25",
      title: "Omniscient Reader's Viewpoint",
      image: "/ORV.jpg",
      link: "https://likemanga.ink/omniscient-reader%E2%80%99s-viewpoint-2168/",
    },
    {
      id: "26",
      title: "Swordmaster's Youngest Son",
      image: "/Swordmaster's Youngest Son.jpg",
      link: "https://likemanga.ink/swordmaster%E2%80%99s-youngest-son-3283/",
    },
    {
      id: "27",
      title: "The Devil Never Cries",
      image: "The Devil Never Cries.jpg",
      link: "https://likemanga.ink/the-devil-never-cries-2738/",
    },
    {
      id: "28",
      title: "Solo Max Level Newbie",
      image: "Solo Max Level Newbie.webp",
      link: "https://asuracomic.net/series/solo-max-level-newbie-9e908932",
    },
    {
      id: "29",
      title: "The World After The End",
      image: "The World After The End.webp",
      link: "https://likemanga.ink/the-world-after-the-fall-2270/",
    },
    {
      id: "30",
      title: "The Beginning After The End",
      image: "The Beginning After The End.jpg",
      link: "https://likemanga.ink/the-beginning-after-the-end-4623/",
    },
    {
      id: "31",
      title: "The Player Hides His Past",
      image: "The Player Who Hides His Past.webp",
      link: "https://likemanga.ink/the-player-hides-his-past-4179/",
    },
    {
      id: "32",
      title: "Regressing With King's Power",
      image: "Regressing With King's Power.webp",
      link: "https://likemanga.ink/regressing-with-the-kings-power-267/",
    },
    {
      id: "33",
      title: "Regressor Of The Fallen Family",
      image: "Regressor Of The Fallen Family.webp",
      link: "https://likemanga.ink/a-flame-reborn-14870/",
    },
    {
      id: "34",
      title: "Dragon Slayer's Peerless Regression",
      image: "Demon Slayer's Peerless Regression.jpeg",
      link: "https://likemanga.ink/a-dragonslayer39;s-peerless-regression-32958/",
    },
    {
      id: "35",
      title: "Regressor Instruction Manual",
      image: "Regressor Instruction Manual.jpeg",
      link: "https://likemanga.ink/regressor-instruction-manual-4812/",
    },
    {
      id: "36",
      title: "Star Embracing Swordmaster",
      image: "Star Embracing Swordmaster.jpeg",
      link: "https://likemanga.ink/star-embracing-swordmaste-8780/",
    },
    {
      id: "37",
      title: "Ranker Who Lives A Second Life",
      image: "Ranker Who Lives A Second Life.jpg",
      link: "https://likemanga.ink/ranker-who-lives-a-second-time-6957/",
    },
    {
      id: "38",
      title: "Invincible After Shocking My Empress Wife",
      image: "Invincible After Shocking My Empress Wife.webp",
      link: "https://likemanga.ink/invincible-after-shocking-my-empress-wife-14723/",
    },
    {
      id: "39",
      title: "Absolute Regression",
      image: "Absolute Regression.webp",
      link: "https://likemanga.ink/absolute-regression-29461/",
    },
    {
      id: "40",
      title: "SSS Ranked Saint Knight",
      image: "SSS Ranked Saint Knight.webp",
      link: "https://likemanga.ink/sss-grade-saint-knight-14899/",
    },
    {
      id: "41",
      title: "Reformation Of The Deadbeat Noble",
      image: "Reformation Of The Deadbeat Noble.jpeg",
      link: "https://likemanga.ink/the-lazy-prince-becomes-a-genius-3035/",
    },
    {
      id: "42",
      title: "The Academy's Genius Swordsman",
      image: "The Academy's Genius Swordsman.jpeg",
      link: "https://likemanga.ink/academy%E2%80%99s-genius-swordmaster-3273/",
    },
    {
      id: "43",
      title: "Academy's Undercover Professor",
      image: "Academy's Undercover Professor.webp",
      link: "https://likemanga.ink/academy%E2%80%99s-undercover-professor-657/",
    },
    {
      id: "44",
      title: "Legendary Hero Is An Honors Student",
      image: "Legendary Hero Is An Honors Student.png",
      link: "https://likemanga.ink/the-legendary-hero-is-an-academy-honors-student-32914/",
    },
    {
      id: "45",
      title: "Solo Leveling Ragnarok",
      image: "Solo Leveling Ragnarok.jpg",
      link: "https://likemanga.ink/solo-leveling-ragnarok-28849/",
    },
    {
      id: "46",
      title: "Martial God Regressed To Level 2",
      image: "Martial God Regressed To Level 2.webp",
      link: "https://likemanga.ink/martial-god-regressed-to-level-2-1981/",
    },
    {
      id: "47",
      title: "The Regressed Son Of The Duke Is An Assassin",
      image: "The Regressed Son Of The Duke Is An Assassin.jpg",
      link: "https://likemanga.ink/the-regressed-son-of-a-duke-is-an-assassin-16402/",
    },
    {
      id: "48",
      title: "The Extra's Academy Survival Guide",
      image: "The Extra's Academy Survival Guide.webp",
      link: "https://likemanga.ink/the-extra%E2%80%99s-academy-survival-guide-14757/",
    },
    {
      id: "49",
      title: "Magic Academy's Genius Blinker",
      image: "Magic Academy's Genius Blinker.webp",
      link: "https://likemanga.ink/magic-academy%E2%80%99s-genius-blinker-24564/",
    },
    {
      id: "50",
      title: "Boundless Necromancer",
      image: "Boundless Necromancer.jpg",
      link: "https://likemanga.ink/boundless-necromancer-3288/",
    },
    {
      id: "51",
      title: "The Regressed Mercenary's Machinations",
      image: "The Regressed Mercinary's Machinations.jpeg",
      link: "https://likemanga.ink/the-regressed-mercenary39;s-machinations-31688/",
    },
    {
      id: "52",
      title: "The Heavenly Demon Can't Live A Normal Life",
      image: "The Heavenly Demon Can't Live A Normal Life.webp",
      link: "https://likemanga.ink/the-heavenly-demon-can%E2%80%99t-live-a-normal-life-1636/",
    },
    {
      id: "53",
      title: "The Illegitimate Who Devours Weapons",
      image: "The Illegitimate Who Devours Weapons.jpeg",
      link: "https://likemanga.ink/the-illegitimate-who-devours-weapons-33841/",
    },
    {
      id: "54",
      title: "Artifact Devouring Player",
      image: "Artifact Devouring Player.jpeg",
      link: "https://likemanga.ink/artifactdevouring-player-33649/",
    },
    {
      id: "55",
      title: "Genius Archer's Streaming",
      image: "Genius Archer's Streaming.jpeg",
      link: "https://likemanga.ink/genius-archer%E2%80%99s-streaming-20627/",
    },
    {
      id: "56",
      title: "I Robbed The Storehouse Of God",
      image: "I Robbed The Storehouse Of God.webp",
      link: "https://likemanga.ink/i-robbed-the-storehouse-of-the-god-31456/",
    },
    {
      id: "57",
      title: "Evolution From Carp To Divine Dragon",
      image: "Evolution From Carp To Divine Dragon.jpeg",
      link: "https://likemanga.ink/evolution-from-carp-to-divine-dragon-20154/",
    },
    {
      id: "58",
      title: "The Crown Prince That Sells Medicine",
      image: "The Crown Prince That Sells Medicine.webp",
      link: "https://likemanga.ink/the-crown-prince-that-sells-medicine-13666/",
    },
    {
      id: "59",
      title: "Talent Swallowing Magician",
      image: "Talent Swallowing Magician.webp",
      link: "https://likemanga.ink/talentswallowing-magician-3701/",
    },
    {
      id: "60",
      title: "Steel Eating Player",
      image: "Steel Eating Player.jpeg",
      link: "https://likemanga.ink/steeleating-player-7531/",
    },
    {
      id: "61",
      title: "Becoming The King By Scavenging",
      image: "Becoming The King By Scavenging.jpeg",
      link: "https://likemanga.ink/i-became-the-king-by-scavenging-16347/",
    },
    {
      id: "62",
      title: "Player Who Can't Level Up",
      image: "Player Who Can't Level Up.jpg",
      link: "https://likemanga.ink/the-player-that-can%E2%80%99t-level-up-1909/",
    },
    {
      id: "63",
      title: "Youngest Scion Of Mages",
      image: "Youngest Scion Of Mages.jpeg",
      link: "https://likemanga.ink/youngest-scion-of-the-mages-4837/",
    },
    {
      id: "64",
      title: "To Hell With Being A Saint",
      image: "To Hell With Being A Saint.webp",
      link: "https://likemanga.ink/the-holy-power-of-modern-medicine-1611/",
    },
    {
      id: "65",
      title: "Overlord Of Insects",
      image: "Overlord Of Insects.jpeg",
      link: "https://likemanga.ink/overlord-of-insects-18311/",
    },
    {
      id: "66",
      title: "I Obtained A Mythic Item",
      image: "I Obtained A Mythic Item.jpeg",
      link: "https://likemanga.ink/i-obtained-a-mythic-item-2268/",
    },
    {
      id: "67",
      title: "Dragon Devouring Mage",
      image: "Dragon Devouring Mage.jpeg",
      link: "https://likemanga.ink/the-mage-swallowed-the-dragon-4190/",
    },
    {
      id: "68",
      title: "SSS Class Suicide Hunter",
      image: "SSS Class Suicide Hunter.webp",
      link: "https://likemanga.ink/sssclass-suicide-hunter-2673/",
    },
    {
      id: "69",
      title: "The Knight Who Returned With A God",
      image: "The Knight Who Returned With A God.jpeg",
      link: "https://likemanga.ink/the-knight-king-who-returned-with-a-god-4116/",
    },
    {
      id: "70",
      title: "Infinite Mage",
      image: "Infinite Mage.webp",
      link: "https://likemanga.ink/infinite-mage-2170/",
    },
    {
      id: "71",
      title: "Overgeared",
      image: "Overgeared.jpg",
      link: "https://likemanga.ink/overgeared-manhwa-1597/",
    },
    {
      id: "72",
      title: "Arcane Sniper",
      image: "Arcane Sniper.jpeg",
      link: "https://likemanga.ink/arcane-sniper-3049/",
    },
    {
      id: "73",
      title: "Pick Me Up Infinite Gacha",
      image: "Pick Me Up Infinite Gacha.webp",
      link: "https://likemanga.ink/pick-me-up-2515/",
    },
    {
      id: "74",
      title: "Murim Login",
      image: "Murim Login.webp",
      link: "https://likemanga.ink/murim-login-1341/",
    },
    {
      id: "75",
      title: "The Magic Tower's Problematic Child",
      image: "The Magic Tower's Problematic Child.jpeg",
      link: "https://likemanga.ink/the-magic-tower%E2%80%99s-problem-child-34166/",
    },
    {
      id: "76",
      title: "Life Of A Magic Academy Mage",
      image: "Magic Academy.webp",
      link: "https://likemanga.ink/life-of-a-magic-academy-mage-2163/",
    },
    {
      id: "77",
      title: "Chronicles Of The Demon Faction",
      image: "Demon Faction.webp",
      link: "https://likemanga.ink/chronicles-of-the-demon-faction-2976/",
    },
    {
      id: "78",
      title: "Eternally Regressing Knight",
      image: "Regressing Knight.webp",
      link: "https://likemanga.ink/eternally-regressing-knight-22263/"
    },
    {
      id: "79",
      title: "Divine Ring Descends",
      image: "Divine.webp",
      link: "https://manhwaclan.com/manga/divine-ring-descends-the-strongest-otherworld/",
    },
  ],
}

export const seriesData: MediaItem[] = [
  {
    id: "1",
    title: "Lucifer",
    image: "Lucifer.jpg",
    link: "",
  },
  {
    id: "2",
    title: "Friends",
    image: "Friends.jpg",
    link: "",
  },
  {
    id: "3",
    title: "How I Met Your Mother",
    image: "How I Met Your Mother.jpg",
    link: "",
  },
  {
    id: "4",
    title: "Flash",
    image: "Flash.jpg",
    link: "",
  },
  {
    id: "5",
    title: "Supergirl",
    image: "Supergirl.jpg",
    link: "",
  },
  {
    id: "6",
    title: "Arrow",
    image: "Arrow.jpg",
    link: "",
  },
  {
    id: "7",
    title: "Person of Interest",
    image: "Person of Interest.jpg",
    link: "",
  },
  {
    id: "70",
    title: "Dark",
    image: "Dark.jpg",
    link: "",
  },
  {
    id: "8",
    title: "Two and a Half Men",
    image: "Two and a Half Men.jpg",
    link: "",
  },
  {
    id: "9",
    title: "Suits",
    image: "Suits.jpg",
    link: "",
  },
  {
    id: "10",
    title: "Loki",
    image: "Loki.jpg",
    link: "",
  },
  {
    id: "11",
    title: "Legends Of Tomorrow",
    image: "Legends Of Tomorrow.jpg",
    link: "",
  },
  {
    id: "12",
    title: "Discovery Of Witches",
    image: "Discovery Of Witches.jpg",
    link: "",
  },
  {
    id: "13",
    title: "Good Doctor",
    image: "Good Doctor.jpg",
    link: "",
  },
  {
    id: "14",
    title: "Teen Wolf",
    image: "Teen Wolf.jpg",
    link: "",
  },
  {
    id: "15",
    title: "House",
    image: "House.jpg",
    link: "",
  },
  {
    id: "16",
    title: "Locke And Key",
    image: "Locke And Key.jpg",
    link: "",
  },
  {
    id: "17",
    title: "Scorpion",
    image: "Scorpion.jpg",
    link: "",
  },
  {
    id: "18",
    title: "God Friended Me",
    image: "God Friended Me.jpg",
    link: "",
  },
  {
    id: "19",
    title: "Legacies",
    image: "Legacies.jpg",
    link: "",
  },
  {
    id: "20",
    title: "Vampire Diaries",
    image: "Vampire Diaries.jpg",
    link: "",
  },
  {
    id: "21",
    title: "Big Bang Theory",
    image: "Big Bang Theory.jpg",
    link: "",
  },
  {
    id: "22",
    title: "Moon Knight",
    image: "Moon Knight.jpg",
    link: "",
  },
  {
    id: "23",
    title: "Money Heist",
    image: "Money Heist.jpg",
    link: "",
  },
  {
    id: "24",
    title: "The Originals",
    image: "The Originals.jpg",
    link: "",
  },
  {
    id: "25",
    title: "The Mentalist",
    image: "The Mentalist.jpg",
    link: "",
  },
  {
    id: "26",
    title: "Lost In Space",
    image: "Lost In Space.jpg",
    link: "",
  },
  {
    id: "27",
    title: "ShadowHunters",
    image: "ShadowHunters.jpg",
    link: "",
  },
  {
    id: "28",
    title: "The Umbrella Academy",
    image: "The Umbrella Academy.jpg",
    link: "",
  },
  {
    id: "29",
    title: "Stranger Things",
    image: "Stranger Things.jpg",
    link: "",
  },
  {
    id: "30",
    title: "Modern Family",
    image: "Modern Family.jpg",
    link: "",
  },
  {
    id: "31",
    title: "She Hulk",
    image: "She Hulk.jpg",
    link: "",
  },
  {
    id: "32",
    title: "Brooklyn 99",
    image: "Brooklyn 99.jpg",
    link: "",
  },
  {
    id: "33",
    title: "Stargirl",
    image: "Stargirl.jpg",
    link: "",
  },
  {
    id: "34",
    title: "Kung Fu",
    image: "Kung Fu.jpg",
    link: "",
  },

  {
    id: "35",
    title: "Charmed",
    image: "Charmed.jpg",
    link: "",
  },
  {
    id: "36",
    title: "Young Sheldon",
    image: "Young Sheldon.jpg",
    link: "",
  },
  {
    id: "37",
    title: "Manifest",
    image: "Manifest.jpg",
    link: "",
  },
  {
    id: "38",
    title: "Community",
    image: "Community.jpg",
    link: "",
  },
  {
    id: "39",
    title: "Berlin",
    image: "Berlin.jpg",
    link: "",
  },
  {
    id: "40",
    title: "Echo",
    image: "Echo.jpg",
    link: "",
  },
  {
    id: "41",
    title: "Imposters",
    image: "Imposters.jpg",
    link: "",
  },
  {
    id: "42",
    title: "DC Titans",
    image: "DC Titans.jpg",
    link: "",
  },
  {
    id: "43",
    title: "The Pitchers",
    image: "The Pitchers.jpg",
    link: "",
  },
  {
    id: "44",
    title: "National Treasure-Edge Of History",
    image: "National Treasure-Edge Of History.jpg",
    link: "",
  },
  {
    id: "45",
    title: "Ozark",
    image: "Ozark.jpg",
    link: "",
  },
  {
    id: "46",
    title: "Taaza Kabar",
    image: "Taaza Kabar.jpg",
    link: "",
  },
  {
    id: "47",
    title: "Asur",
    image: "Asur.jpg",
    link: "",
  },
  {
    id: "48",
    title: "Superman And Lois",
    image: "Superman And Lois.jpg",
    link: "",
  },
  {
    id: "49",
    title: "The Rookie",
    image: "The Rookie.jpg",
    link: "",
  },
  {
    id: "50",
    title: "Wanda And Vision",
    image: "Wanda And Vision.jpg",
    link: "",
  },
  {
    id: "51",
    title: "Jack Ryan",
    image: "ack Ryan.jpeg",
    link: "",
  },
  {
    id: "52",
    title: "Reacher",
    image: "Reacher.jpg",
    link: "",
  },
  {
    id: "53",
    title: "Squid Games",
    image: "Squid Games.jpg",
    link: "",
  },
  {
    id: "54",
    title: "Breaking Bad",
    image: "Breaking Bad.jpeg",
    link: "",
  },
  {
    id: "55",
    title: "The White Collar",
    image: "The White Collar.jpg",
    link: "",
  },
  {
    id: "56",
    title: "Lie To Me",
    image: "Lie To Me.jpg",
    link: "",
  },
  {
    id: "57",
    title: "High Potential",
    image: "High Potential.jpg",
    link: "",
  },
  {
    id: "58",
    title: "Cobra Kai",
    image: "Cobra Kai.jpg",
    link: "",
  },
  {
    id: "59",
    title: "Iron Fist",
    image: "Iron Fist.jpg",
    link: "",
  },
  {
    id: "60",
    title: "Daredevil",
    image: "Daredevil.jpg",
    link: "",
  },
  {
    id: "61",
    title: "Falcon And The Winter Soldier",
    image: "Falcon And The Winter Soldier.jpg",
    link: "",
  },
  {
    id: "62",
    title: "Hawkeye",
    image: "Hawkeye.jpg",
    link: "",
  },
  {
    id: "63",
    title: "The Secret Invasion",
    image: "The Secret Invasion.jpg",
    link: "",
  },
  {
    id: "65",
    title: "What If?",
    image: "What If.jpg",
    link: "",
  },
  {
    id: "66",
    title: "Ms Marvel",
    image: "Ms Marvel.jpg",
    link: "",
  },
  {
    id: "67",
    title: "Agatha All Along",
    image: "Agatha All Along.jpg",
    link: "",
  },
  {
    id: "68",
    title: "Marvel Zombies",
    image: "Zombies.jpg",
    link: "",
  },
  {
    id: "69",
    title: "The Boys",
    image: "Boys.jpg",
    link: "",
  },
  {
    id: "70",
    title: "Gen V",
    image: "Gen V.jpg",
    link: "",
  },
  {
    id: "71",
    title: "Raising Hope",
    image: "Hope.jpg",
    link: "",
  },
]
